### PR TITLE
move 17-conditionnals to 13-conditionnals

### PR DESCRIPTION
**Pull request by amasson84**
Moving the chapter 17 (conditionnals) to 14
---
I think conditionals should be after the loops as they usually are used together and at the end of the class students might be too tired to catch the important notion of condition.
Also, the chapter  ```Writing Functions```has exercises that use conditions so conditions should be seen before this chapter.

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.  

---

### CODE REVIEW

**Comment by alee** [comment]
thanks for the PR! I don't know if you caught the discussion at https://github.com/swcarpentry/python-novice-gapminder/issues/462 - would you like to chime in there as well? I think the current mini-consensus is for the numbering:

12 - for loops
13 - conditionals
14- looping over data sets
15-beverage break
16-writing functions
17-scope
18-programming style

If you think this sounds reasonable as well, would you be willing to adjust the PR to match that ordering?

**Comment by amasson84** [comment]
I change the PR corresponding to what you suggest.
Sorry, I didn't know you have a discussion about it, I suggested this as my contribution for my teacher training ;)

**Comment by vahtras** [comment]
Looks good to me

**Comment by slel** [comment]
Note: "conditional" ends with "-tional" not "-tionnal".

**Pull request merged**
