### PR TITLE
Added `random.choice` as sampling option (581)

### LINKED ISSUE #581: Selecting random character from string (Ep. 6) missing a good solution
The challenge "[Locating the right module](http://swcarpentry.github.io/python-novice-gapminder/06-libraries/index.html#locating-the-right-module)" has several solutions, but I think the most obvious one is missing.

The solutions given are:

```python
print(bases[random.randrange(len(bases))])
print(bases[random.randint(0, len(bases) - 1)])  # implied
print(random.sample(bases, 1)[0])
```

with the postscript "\[There are] also other functions you could use, but with more convoluted code as a result." What about this?

```python
print(random.choice(bases))
```

This is, I would argue, the most keystroke-efficient solution and most intuitive to read; it certainly does not fall into the "more convoluted" category. Is the reason for missing it out because it answers exactly the use case in the challenge, and is therefore not applicable to adjacent challenges (e.g. picking more than one distinct character; doing something else with the index)?

### PR DESCRIPTION
**Pull request by guydav**
Also removed the reference to being able to find more convoluted ways to solve the problem, as suggested in the issue discussion.

Resolves #581 .

### CODE REVIEW

**Comment by alee** [comment]
Hi @guydav - this LGTM and I'm happy to merge, but for posterity you should put these changes on a branch in your fork to avoid future issues with keeping your fork and this upstream repository synced. You could always delete and re-fork but it's a good habit to always submit pull requests to upstream from a new branch in your fork.

**Comment by guydav** [comment]
Hi @alee -- I don't know how I forgot to do that, my apologies. Would you prefer if resubmit the PR in a separate branch?

**Comment by alee** [comment]
If you have the time and would like the GitHub practice that's fine, otherwise just wanted you to be forewarned that after merging your fork's gh-pages and this upstream will be out of sync and you'll likely have to do some Git surgery to get things lined up again

**Comment by alee** [comment]
Great! You should be able to do it straight from the GitHub web interface by clicking on the branch dropdown at the top left of the Code tab:

image

As soon as the branch is created you can submit the PR from it. Don't worry about bringing the branch up to date with upstream, I don't think there are any conflicts. 

After that's done you'll still need to reset your fork's gh-pages to bring it in line with upstream though..

**Comment by guydav** [comment]
Done. See #592

**Pull request closed without merging**
