### PR TITLE
Show popular StackOverflow questions, not newest

### PR DESCRIPTION
**Pull request by katrinleinweber**
Is it likely that our learners want to see whichever questions were asked there recently? If not, please consider this update that sends them to the popular questions (which IMHO are likely more relevant and of exemplary quality).

### CODE REVIEW

**Comment by katrinleinweber** [comment]
PS: If you agree, I would send this same PR to [more lessons](https://github.com/search?l=Markdown&o=desc&q=org%3Acarpentries+org%3Aswcarpentry+org%3Adatacarpentry+org%3Alibrarycarpentry+stackoverflow+tagged+NOT+Votes&s=indexed&type=Code)

**Comment by vahtras** [comment]
Good idea

**Comment by alee** [comment]
thanks @katrinleinweber !

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
