### PR TITLE
Add necessary files to the binder branch

### PR DESCRIPTION
**Pull request by davidrpugh**
This PR add necessary files to the `binder` branch of the `python-novice-gapminder` lessons. Will open a separate PR to add the Binder button to the main `README.md`.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@alee Do we need to include the `_site` directory in this repo? I thought that we had agreed that it would be best not to include the lesson materials inside the Binder instance.

**Comment by davidrpugh** [comment]
@alee Let's finalize what we want to include in this branch. Once this PR is merged, then you can merge PR #406 which adds the binder button to the `gh-pages/README.md`.

**Comment by djinnome** [comment]
I have a few thoughts on this topic.  There are a number of arguments for including or not including different aspects of the lesson materials, depending on the use case. Let's enumerate the possibilites:

1. **Live workshop student**: completely empty binder with only the data and prerequisites, and no notebooks.
2. **Teacher practice**: skeleton notebooks, with markdown, but empty code cells.
3. **Self-study**:  notebooks with markdown and code cells, but no outputs
4. **Teacher solution manual**: notebooks with markdown and code cells, with outputs.

My thought is that each of these could be a different branch, with a different binder URL, corresponding to the different use cases.

**Comment by davidrpugh** [comment]
@djinnome the use case that I had in mind was your number 1 (so I removed the `notebooks` dir to have clean repo with only the `data` director and the `environment.yml` file.  I think use cases 2-4 make sense as separate branches but I think we should make those separate PR(s).  

@alee apologies but for some reason I thought the `_site` directory was included in the branch because it was showing up my my local machine but it is being ignored.

**Comment by davidrpugh** [comment]
@alee JupyterLab 1.0 is out on `conda-forge` so I added the channel and bumped the version number, once Jupyterlab 1.0 is released on the `main` channel then I will remove the `conda-forge` channel to keep the `environment.yml` file as simple as possible.

The environment file will already download Pandas 0.24.2: if you specify the major and minor version numbers but leave the patch version unspecified, then Conda will download the most recent patch by default.

**Comment by alee** [comment]
Thanks for the clarification! I didn't realize patch versions would be included by default, I don't use conda much, typically just pipenv or pip :-).

Looks good to me, I'll merge shortly.

**Pull request merged**
