### PR TITLE
Update 09-plotting.md

### PR DESCRIPTION
**Pull request by narayananr**
The plotting lesson uses "for loops" to get the "year" values from the column names. However, for loop is  introduced later. Instead of for loop, we can use pandas' function to get the year from column names.
`years = data.columns.str.strip('gdpPercap_')
`
instead of the for loop code chunk
`years=[]
for col in data.columns:
     year = col[-4:]
     years.append(year)
`

### CODE REVIEW

**Comment by souravsingh** [comment]
@narayananr Is there going to be an effect in the learning for newcomers with this change?

**Comment by ErinBecker** [comment]
@narayananr - Thank you for noticing that the for loops are introduced in the lesson after the first time they're used. It's always tricky to keep things in order! 

@souravsingh - I'm not sure whether the best move here is 1) adding the pandas' function here, 2) simplifying the example so that a for loop isn't needed, or 3) moving the introduction to for loops to earlier in the lesson. Maybe your co-maintainers have some thoughts?

**Comment by narayananr** [comment]
thanks for getting back. I found this while teaching the lesson and suggested pandas option as the previous lesson and this is using Pandas. Moving for loops ahead is definitely an option. I think either way is fine.

**Comment by ntmoore** [comment]
I think that we should not move the for loop earlier.  For loops are two lessons later (lesson 12, after lists).  Instead, simplifying this example (to remove for loops and replace with pandas function) seems like a reasonable approach.  pandas and for-loops are both significant cognitive loads for learners - I think its important to keep them separate.

**Comment by souravsingh** [comment]
Sounds good to me.

**Pull request merged**
