### PR TITLE
Error messages

### PR DESCRIPTION
**Pull request by cgeroux**
This pull request includes the start of the content for a lesson 5 "error messages".

This was to be part of my instructor training checkout, but I realized after the fact that it said "Submit a small change to one of our lessons". This might be a bit more than a small change (mostly an addition). 

I hope it will be a useful starting point for a lesson 5, but if it does not fit the lesson style well enough feel free to just drop it. If required I can make some other small change for the instructor training checkout procedure.

Note: I also submitted a pull request for a number of small typo-like fixes. See the "small changes" pull request. This branch builds on the "small changes" branch. So including just this pull request should get both of them.

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks very much, Chris - I'll review and merge the first one, then ask you to merge that into this so that this one lands the episode 5 stuff on its own.  Thanks very much for all your hard work.

**Comment by cgeroux** [comment]
Ok, sounds good.

**Comment by gvwilson** [comment]
Thanks for the material - can you please:
1. Sync with what's in the repo.
2. Re-submit a PR containing only episode 5 (this PR contains changes to other files as well).
Thanks,
Greg

**Comment by cgeroux** [comment]
Ok, started working on this, however, I now get a conflict with the work I did in episode 5. Looks like you added some content to episode 5 since I made these changes. The question now becomes, how should I resolve the conflict. Through out your changes, through out may changes, or merge the content some how. Seems like we might need to talk a bit about what to do here.

**Comment by gvwilson** [comment]
I'm happy to do the merge.

**Comment by cgeroux** [comment]
Closing this pull request in favor of the newer one.

**Pull request closed without merging**
