### PR TITLE
edits to standardize the format of exercises

### PR DESCRIPTION
**Pull request by eldobbins**
This PR is to address issues described in #461, which describes an exercise whose formatting could be improved.  While working on that exercise, I found a couple more with formatting oddities, so fixed them too.

* `Order of Operations`
  * added numbering to match questions with solutions
  * reordered the questions so that the function parse_dates() is introduced before it is asked about
  * added a 3rd question about the `None` returned by parse_dates()
* removed the Python block formatting from `Calling by Name` because I think that section is part of the questions not part of the code
* added spaces to the items list in `Encapsulating Data Analysis` so the Markdown is parsed correctly
* `Encapsulate of If/Print Block`
  * fixed typo in the title
  * added and removed spaces from code examples to be more PEP8

I'm not satisfied with the wording of that last exercise.  It asks 2 questions and then solves them before asking 2 more whose answers are in the Solutions block.  I see that the exercise author is trying to chain concepts, but I'm not 100% sure it's successful. Please let me know if you want me to reformulate that exercise as part of this PR

### CODE REVIEW

**Comment by alee** [comment]
Reformulation of the exercise would be welcome, but we can have a separate PR for that - thanks again!

**Comment by eldobbins** [comment]
Maybe we could close the original issue #461 ?

**Comment by eldobbins** [comment]
I just checked the formatted rendering of the changes I made, and it's all screwed up.  I'm going to try and fix that.  I still have the branch.   Can this PR be reopened or should I start a new one?

**Comment by eldobbins** [comment]
OK.  I've fixed the formatting problems.  The fixes are in the original branch.  Please let me know how I should submit it.

**Comment by eldobbins** [comment]
Issued a new PR to fix this rendering problem.

**Pull request merged**
