### PR TITLE
add anaconda navigator instructions in 'Running and Quitting' episode

### PR DESCRIPTION
**Pull request by K-Meech**
Adds instructions for opening JupyterLab via anaconda navigator - for issue: https://github.com/swcarpentry/python-novice-gapminder/issues/516

I tested this on a new Anaconda installation on Windows. I believe the Mac instructions are also correct, but it would be good to check with a mac user that:
- the instructions also work for them
- the anaconda navigator interface looks similar to the screenshot in the lesson

### CODE REVIEW

**Comment by paultgriffiths** [comment]
Finding things via Spotlight [can be temperamental ](https://apple.stackexchange.com/questions/62715/applications-dont-show-up-in-spotlight) so a belt-and-braces approach (if required) might be to include the option to Command-Shift-G in Finder and then type /Applications to be sure to go to the Mac Applications folder.

**Review by alee — APPROVED** [review]
Thanks @K-Meech ! I made some minor edits, if you think they look OK I'm happy to merge in (so long as no other @swcarpentry/python-novice-gapminder-maintainers have any objections)

**Comment by alee** [comment]
Thanks for the heads up @paultgriffiths - do you think the current set of instructions is sufficient? I don't want to overwhelm with too many options at this point and would prefer to keep things as succinct as possible.

> Finding things via Spotlight [can be temperamental ](https://apple.stackexchange.com/questions/62715/applications-dont-show-up-in-spotlight) so a belt-and-braces approach (if required) might be to include the option to Command-Shift-G in Finder and then type /Applications to be sure to go to the Mac Applications folder.

**Comment by K-Meech** [comment]
> Thanks @K-Meech ! I made some minor edits, if you think they look OK I'm happy to merge in (so long as no other @swcarpentry/python-novice-gapminder-maintainers have any objections)

All looks good to me @alee!

**Comment by paultgriffiths** [comment]
> Thanks for the heads up @paultgriffiths - do you think the current set of instructions is sufficient? I don't want to overwhelm with too many options at this point and would prefer to keep things as succinct as possible.
> 
> > Finding things via Spotlight [can be temperamental ](https://apple.stackexchange.com/questions/62715/applications-dont-show-up-in-spotlight) so a belt-and-braces approach (if required) might be to include the option to Command-Shift-G in Finder and then type /Applications to be sure to go to the Mac Applications folder.

Definitely sufficient - on most modern Macs, the Spotlight database updates pretty quickly, so Spotlight should find things after they've been installed.  If not, going to Applications will definitely work.

**Pull request merged**
