### PR TITLE
update diagrams to SVG

### LINKED ISSUE #349: SVG versions of diagrams of chapter 9
Dear maintainers,
currently all diagrams obtained from matplotlib are rendered using PNG. I intend to work/have worked
on regenerating them as SVG files. I will submit a separate pull request later on.
Note, that this will also form my contribution as part of the instructor checkout process.

### PR DESCRIPTION
**Pull request by CaptainSifff**
This updates the figures that I was able to reproduce to SVG format and would close #349 .

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Sure, will have a look.

**Comment by maxim-belkin** [comment]
@CaptainSifff, could you please re-create figures with the following option enabled?
```python
import matplotlib.pyplot as plt
plt.rcParams['svg.fonttype'] = 'none'
```
At the moment, all text is converted to paths.

**Comment by alee** [comment]
Thanks @CaptainSifff 👍 

@maxim-belkin whenever you get a chance could you please re-review? Thanks!

**Comment by maxim-belkin** [comment]
Hey, @CaptainSifff (and @alee)!
SVG files are much better now, though they now highlight some lameness of SVG engine in matplotlib. So, here is how you can improve them further (I'm using file `9_correlations_solution1.svg` below as an example).
1. Delete this block
```svg
 <defs>
  <style type="text/css">
*{stroke-linecap:butt;stroke-linejoin:round;}
  </style>
 </defs>
```
2. Install either `scour` or `svgcleaner` and execute one of the following two commands:
```sh
scour --set-precision=1 \
      --disable-simplify-colors \
      --create-groups \
      --enable-viewboxing \
      --nindent=2 \
      --strip-xml-space \
      --enable-id-stripping \
      --shorten-ids \
      --enable-comment-stripping \
      -i 9_correlations_solution1.svg \
      -o cleaned.svg

# or

svgcleaner --indent 2 \
           --ungroup-defs no \
           --multipass \
            --coordinates-precision 1 \
            --properties-precision 1 \
            --paths-coordinates-precision 1 \
            9_correlations_solution1.svg \
            cleaned.svg
```
**Notes:** 

   * `svgcleaner`
       - converts `rect` to a `path`. I can't really explain why. If you're using `svgcleaner`, check what `rect` was in the original file and replace the corresponding `path` in the file that you got with it. 
   * `scour`
      - scatters `defs` across the file, which is ... weird. If you're using `scour`, combine all `defs` block into one. 
      - keeps `transform="rotate(-0 ... ...)"`. Remove those as they do nothing (they rotate by 0 degrees around some point).
      - uses 6 digits for colors (e.g. `#000000` and `#ffffff`). You can shorten these up a bit. For example, for black color you can use `#000`.

Regardless of the tool you use, you'll end up with almost the same result.

3. (Optional) Round up (or down) all numbers (remove mantissa). This step is optional because it has to be done manually.

4. Manual parts that I'm not sure how to automate (except in Vim):
 * remove `font-family="DejaVu Sans"`
 * remove `stroke-width=".8"` (it will default to `1`)
 * group together alike elements. That is, change this:
```
  <use x="57.417264" y="307.584" stroke="#000" xlink:href="#b"/>
  <text x="57.417264" y="322.182437" font-size="10px" text-anchor="middle">300</text>
  <use x="110.378074" y="307.584" stroke="#000" xlink:href="#b"/>
  <text x="110.378074" y="322.182437" font-size="10px" text-anchor="middle">400</text>
``` 
to this
```
  <use x="57.417264" y="307.584" stroke="#000" xlink:href="#b"/>
  <use x="110.378074" y="307.584" stroke="#000" xlink:href="#b"/>

  <text x="57.417264" y="322.182437" font-size="10px" text-anchor="middle">300</text>
  <text x="110.378074" y="322.182437" font-size="10px" text-anchor="middle">400</text>
```
Once you've done that, you'll see that it makes sense to group together all text elements like this:
```svg
  <g font-size="12">
    <g text-anchor="middle">
      <text x="236" y="336">min</text>
      <text transform="matrix(0 -1 1 0 6 175)">max</text>
      <text x="57" y="322">300</text>
      <text x="110" y="322">400</text>
      <text x="163" y="322">500</text>
      <text x="216" y="322">600</text>
      <text x="269" y="322">700</text>
      <text x="322" y="322">800</text>
      <text x="375" y="322">900</text>
    </g>
    <g text-anchor="end">
      <text x="51" y="266">40000</text>
      <text x="51" y="209">60000</text>
      <text x="51" y="152">80000</text>
      <text x="51" y="96">100000</text>
    </g>
  </g>
```

5. `matplotlib` does not use SVG `circle` for data markers, so you have to change it yourself. 

In the end here is the optimized SVG file I got for `9_correlations_solution1.svg`

```
<svg height="346pt" width="461pt" viewBox="0 0 461 346" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

  <defs>
    <circle id="b" cx="0" cy="0" r="3"/> <!-- Data point marker -->
    <path id="c" d="m0 0v4" stroke="#000"/> <!-- vertical ticks -->
    <path id="d" d="m0 0h-4" stroke="#000"/> <!-- horizontal ticks -->
  </defs>

  <!-- data points -->
  <g fill="#1f77b4" stroke="#1f77b4">
    <use x="74"  y="68"  xlink:href="#b"/>
    <use x="84"  y="54"  xlink:href="#b"/>
    <use x="104" y="105" xlink:href="#b"/>
    <use x="84"  y="146" xlink:href="#b"/>
    <use x="88"  y="65"  xlink:href="#b"/>
    <use x="95"  y="207" xlink:href="#b"/>
    <use x="123" y="280" xlink:href="#b"/>
    <use x="102" y="296" xlink:href="#b"/>
    <use x="82"  y="276" xlink:href="#b"/>
    <use x="118" y="261" xlink:href="#b"/>
    <use x="222" y="273" xlink:href="#b"/>
    <use x="399" y="241" xlink:href="#b"/>
  </g>

  <!-- ticks -->
  <g stroke="#000" stroke-width=".8">
    <use x="58"  y="308" xlink:href="#c"/>
    <use x="110" y="308" xlink:href="#c"/>
    <use x="163" y="308" xlink:href="#c"/>
    <use x="216" y="308" xlink:href="#c"/>
    <use x="269" y="308" xlink:href="#c"/>
    <use x="322" y="308" xlink:href="#c"/>
    <use x="375" y="308" xlink:href="#c"/>
    <use x="58"  y="262" xlink:href="#d"/>
    <use x="58"  y="205" xlink:href="#d"/>
    <use x="58"  y="149" xlink:href="#d"/>
    <use x="58"  y="92"  xlink:href="#d"/>
  </g>

  <!-- LABELS -->
  <g font-size="12">
    <!-- X axis -->
    <g text-anchor="middle">
      <text x="236" y="336">min</text>
      <text x="0"   y="0" transform="matrix(0 -1 1 0 6 175)">max</text>
      <text x="57"  y="322">300</text>
      <text x="110" y="322">400</text>
      <text x="163" y="322">500</text>
      <text x="216" y="322">600</text>
      <text x="269" y="322">700</text>
      <text x="322" y="322">800</text>
      <text x="375" y="322">900</text>
    </g>

    <!-- Y axis -->
    <g text-anchor="end">
      <text x="51" y="266">40000</text>
      <text x="51" y="209">60000</text>
      <text x="51" y="152">80000</text>
      <text x="51" y="96">100000</text>
    </g>
  </g>

  <!-- rectangle -->
  <rect x="58" y="42" width="357" height="266" fill="none" stroke="#000"/>
</svg>
```

I'm not sure you guys want to go through all the steps. The most important ones are 1, 2, and 4.
Let me know if you need more help / info / etc.

**Comment by CaptainSifff** [comment]
OK, I have removed the clip path definitions. Anything else?

**Comment by alee** [comment]
Haha, I was waiting to see how deep that rabbit hole goes! Thanks so much @CaptainSifff and @maxim-belkin - I learned a lot from this too!

**Pull request merged**
