### PR TITLE
Add custom binder button

### PR DESCRIPTION
**Pull request by davidrpugh**
This PR adds a custom binder button to Launch JupyterLab.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@alee I have tried to perform the interactive rebase to squash commits ee54088, ea7b96a, and 4fa190f but was never successful. When I ran `git rebase -i` and squashed commits ee54088, ea7b96a into 4fa190f. I could not push those changes to the remote branch without first pulling from the remote branch which added even more unnecessary commits to the PR. When I rebased and squashed before creating the PR, I was able to merge with `swcarpentry:gh-pages` for some reason.

I only changed 1 line in the `README.md`. It looks like those "extra commits" are commits that I made to `kaust-vislab:gh-pages` that are changes intended for my fork only and that I did not intend for `swcarpentry:gh-pages`.

**Comment by alee** [comment]
Doh, sorry to hear it! I think you can get around this by cherry picking your commit or using a different branch to start from, but let me see if I can do some surgery on this branch. I might not be able to get to it until Thursday afternoon or Friday though.

**Comment by alee** [comment]
Thanks David! I assume the unwieldy embedded data is to spell out `JupyterLab`?

**Comment by davidrpugh** [comment]
Yes. Exactly. For reference I used this binder badge generator:

https://mybinder.readthedocs.io/en/latest/howto/badges.html

Would be interested in the Git magic you used to fix up the commits properly in case something similar happens again...

**Pull request merged**
