### PR TITLE
removed for loop and lists from plotting section

### PR DESCRIPTION
**Pull request by timothylwarren**
This is a minor contribution reordering some bits of the plotting episode so as not to mention for loops or lists, which are in a subsequent episode.

### CODE REVIEW

**Comment by souravsingh** [comment]
I believe preserving the exercise as a homework would be good idea.

**Comment by vahtras** [comment]
This is an improvement. Yes an exercise later is ok.

**Comment by alee** [comment]
:+1: to moving the accumulator exercises to episode 12. We can add commits to this PR to preserve context or we could make a separate issue for it - thoughts?

**Comment by vahtras** [comment]
Better to uncouple to separate issues in my opinion.

**Comment by alee** [comment]
Done, added #304 to track this

**Pull request merged**
