### PR TITLE
Improve solution to exercise in For Loop episode

### PR DESCRIPTION
**Pull request by santisoler**
Improve the explanation of the solution for the "Identifying Variable
Name Errors" exercise in the For Loops episode (12). Rearrange the
expected errors to mimic the order in which they they would appear as we
solve them. Add missing expected error for undefined variable `a`.

### CODE REVIEW

**Review by vahtras — APPROVED** [review]
Looks good tome

**Comment by santisoler** [comment]
I'm glad to be helpful. I was wondering if there's a way to put each one of the sentences I created as bullet items. I tried to do so, but the text was looking odd (fonts in purple and as they were inside the code block):

image

If there isn't an easy way to do that, I'm ok with how it looks right now.

**Comment by alee** [comment]
Thanks for the PR @santisoler ! In order to get it to render properly add a newline after your bulleted items, e.g.,

```
> {: .language-python}
> > ## Solution
> > - Python variable names are case sensitive: `number` and `Number` refer to different variables.
> > - The variable `message` needs to be initialized as an empty list.
> > - We want to add the string `"a"` to `message` and not the undefined variable `a`.
> > 
> > ~~~
...
```

> I'm glad to be helpful. I was wondering if there's a way to put each one of the sentences I created as bullet items. I tried to do so, but the text was looking odd (fonts in purple and as they were inside the code block):
> 
> ```
> > {: .language-python}
> > > ## Solution
> > > * Python variable names are case sensitive: `number` and `Number` refer to
> > > different variables.
> > > * The variable `message` needs to be initialized as an empty list.
> > > * We want to add the string `"a"` to `message` and not the undefined variable
> > > `a`.
> ```
> 
> image
> 
> If there isn't an easy way to do that, I'm ok with how it looks right now.

**Comment by santisoler** [comment]
Thanks @alee for the tip! I just changed the sentences to a bullet list, which I think looks better.

I've also noticed that I messed with the type of the `message` variable: it's supposed to be a string and not a list! Already fixed that!

So feel free to merge if you agree.

**Pull request merged**
