### PR TITLE
Change the variable name "sum" to "summatory"

### PR DESCRIPTION
**Pull request by AbrahamAvelar**
As "sum" is a built-in function, it is better to name this variable something different.

### CODE REVIEW

**Review by alee — CHANGES_REQUESTED** [review]
Thanks for taking the time to improve our lesson with this PR! I agree completely that we should not use any of the [built-in methods](https://docs.python.org/3/library/functions.html) as variable names. That said, `summatory` is a bit arcane, can we use something like `cumulative_sum` or `total` instead?

**Comment by vahtras** [comment]
A practice that is not uncommon is to append an underscore to a variable name that conflicts with a built-in, e.g. in this case `sum_`.

**Comment by AbrahamAvelar** [comment]
I agree that cumulative_sum or total may be better. sum_ is good too but I think may be confussing to novices. Anyways I believe the important think is to change the original name from the lesson as it is confussing, even more as in the method sum() is used in the "Writing Functions" episode. When running sequencially, the error comes from python trying to use it as a variable name.

**Comment by alee** [comment]
> I agree that cumulative_sum or total may be better. sum_ is good too but I think may be confussing to novices. Anyways I believe the important think is to change the original name from the lesson as it is confussing, even more as in the method sum() is used in the "Writing Functions" episode. When running sequencially, the error comes from python trying to use it as a variable name.
> How do we get the change in the SC lesson?

If you're OK with `cumulative_sum` or `total` I'd be happy to merge after renaming `summatory` -> `cumulative_sum` - you can do this by adding another commit to your PR branch. Let us know if you need help with it, and thanks again for the PR!

**Review by alee — APPROVED** [review]

**Pull request merged**
