### PR TITLE
Update style to v9.4.0

### PR DESCRIPTION
**Pull request by rgaiacs**
A few changes on style.
Need manual changes at CONTRIBUTING.md!

### CODE REVIEW

**Comment by souravsingh** [comment]
@rgaiacs Thanks for the PR. I am interested to know if the patch works properly, since there are a lot of changes to track.

**Comment by vahtras** [comment]
LGTM

**Comment by alee** [comment]
I tested locally via `git fetch upstream pull/305/head:style-update && git checkout style-update` and on cursory glance all episodes still render fine. @rgaiacs what manual changes need to be applied to the CONTRIBUTING.md? (besides the not-exactly 2 reviewers per lesson :grin:)

**Comment by souravsingh** [comment]
Ok. I checked the changes just now. Looks fine by me.

**Comment by alee** [comment]
Ok, I went ahead and merged - I tagged the repo at https://github.com/swcarpentry/python-novice-gapminder/releases/tag/v0.9.3 before the merge in case we need to revert.

**Comment by rgaiacs** [comment]
> what manual changes need to be applied to the CONTRIBUTING.md?

https://github.com/swcarpentry/lesson-example/pull/186/files#diff-6a3371457528722a734f3c51d9238c13L72

**Pull request merged**
