### PR TITLE
add challenge that introduces the dir command

### PR DESCRIPTION
**Pull request by ntmoore**
I think the dir function/command is very useful for finding out what functions are available for a given data object.  Given that this is an optional side-project, I included an introduction to the topic as a challenge.

Note, I totally waved my hands and glossed over the "double underscore" data/functions that dir returns.  Someone with more expertise in python should (1) fix my terminology and (2) decide what level of description is necessary for those components.

further modifications (PR's) on this are requested!

### CODE REVIEW

**Comment by ntmoore** [comment]
Olav, I can't remember how to make my PR's editable (or PR-able) by other people.  There must be a button...

**Comment by ntmoore** [comment]
Thanks for the feedback @alee. I spent 10 minutes looking for the button you mentioned but it doesn't seem to be available after the PR has been submitted?  Apologies if I'm missing something really obvious!

Would it be easiest to merge it in as is and then follow up with the double-underscore edit when you have time next week?  As its my PR, I will defer to your timing.

**Comment by ntmoore** [comment]
@alee , FYI, from the github help desk:
---
Hi Nathan,

Thanks for getting in touch. The feature you're referring to only applies to forks. It allows people with write access to the upstream repo (i.e the repo you forked from) to push changes to your PR branch.

Anyone with write access to a repo can change any branch that doesn't have branch protections, so anyone with write access to swcarpentry/python-novice-gapminder can already push changes to your branch.

Let me know if you have any more questions.

Cheers,
Jamie

**Comment by alee** [comment]
Ah I see what's going on now. Pull requests typically come from a repository fork (e.g., https://github.com/ntmoore/python-novice-gapminder) but this PR was made directly via a branch on this repository. 

For future reference all maintainers can commit these types of PR branches directly by checking out the branch from this repository and pushing to it (e.g., a9ba7b2e2f3f3c93f60d281b9e32d7f4c6c79cf6)

**Comment by eldobbins** [comment]
I think this PR could be closed since the addition seems pretty stable - at least until I suggested changes to the exercise in #518.

**Pull request merged**
