### PR TITLE
Merge changes to gh-pages and edit Episode 02

### PR DESCRIPTION
**Pull request by vinisalazar**
This is an attempt at starting to work on the `narrative` branch (see discussion on #463).

If merged, this PR will:
 - merge latest changes from `gh-pages` branch.
 - Edit Episode 02 according to the lesson story line (8acfda0)

For future PRs to this branch, is it okay to bring the latest changes from `gh-pages` every time, or should I avoid this?

Thank you for any assistance you can provide,

Vini

### CODE REVIEW

**Comment by alee** [comment]
no, we should not be merging gh-pages back into this narrative branch - it will make for a very confused commit history. If it's not too much trouble please resubmit with just your episode changes in the narrative branch. If you want to work off the latest gh-pages we can fast forward narrative to match gh-pages before you begin your work..

**Comment by vinisalazar** [comment]
Sure, that makes sense. Thank you @alee !

**Comment by alee** [comment]
argh. So my fears came to pass - the commit history has diverged and will create more problems down the road. It may have been because I used the rebase and merge instead of a regular merge but regardless we'll need to redo the branch history a bit to clean it up.

I'll force update the narrative branch to be up to date with gh-pages, can you resubmit your changes as a PR afterwards?

**Comment by alee** [comment]
just a heads up, this caused divergent history in the narrative branch so I rehomed your pull request against an up to date narrative branch (#550).

In the future I don't think we should worry about merging gh-pages back into narrative, just focus on the changes you'd like to make and we'll deal with any merge conflicts in the final PRs from narrative to gh-pages.

Thanks!

**Pull request merged**
