### PR TITLE
updated loop example

### PR DESCRIPTION
**Pull request by isaac-galvan**
Hello,

I added a different example based on the feedback from #111 

Thanks for reviewing!

### CODE REVIEW

**Comment by souravsingh** [comment]
The PR looks good to me.

**Comment by souravsingh** [comment]
I can merge this if no one else has any problems

**Comment by alee** [comment]
Thanks for the PR @isaac-galvan ! However, I'm not quite convinced that this a clear improvement over the original example. This for loop could also be boiled down to `results = original[1::2]` which raises the question of why even use a for loop.

Perhaps we can lift one of the examples from http://swcarpentry.github.io/python-novice-inflammation/02-loop/index.html - IMO it makes sense for the @swcarpentry/python-novice-gapminder-maintainers and @swcarpentry/python-novice-inflammation-maintainers to develop a shared set of compelling examples since there's a lot of overlap between the lessons.

**Comment by maxim-belkin** [comment]
Thanks for tagging us, @alee.

With regards to "reversing a string" exercise: I tend to agree that it has to be changed because (a) how often do we loop over a string in real life? and (b) we can achieve the same effect with `[::-1]`. I also agree with @alee's concerns that suggested exercise can be "solved" with `[1::2]` so... it's not that much different. It seems that we need an exercise that is a tiny bit more complex. Complexity can come from the need to check certain quality(-ies) of the list elements -- first character, type, etc.

Our lesson talks about loops before lists so we can't actually do this switch right now: there is an effort to change the order of episodes but it's a WIP. Your lesson talks about lists before loops, so you're all good.

**Comment by eldobbins** [comment]
Update: it seems the order of the lessons has been changed so that now lists comes before loops. So we should be able to make progress now on the PR.  But if this solution has been rejected, perhaps this PR should be closed?

If not closed, is it possible for me to modify it in my fork?  Not sure of the git procedure here.

**Pull request closed without merging**
