### PR TITLE
Cutting material based on feedback

### PR DESCRIPTION
**Pull request by gvwilson**
Cutting:

* lists
* defensive programming
* arrays

Reducing:

* error messages
* reading tabular data
* plotting
* loops
* conditionals
* writing functions
* programming style
* wrap-up

### CODE REVIEW

**Comment by lexnederbragt** [comment]
I hate to see lists go, and running python scripts outside of the notebook, but I see no other way (this is difficult planning!). BTW lists is still mentioned in the 'Learners Will Be Able To...' part.

**Comment by gvwilson** [comment]
Thanks - I've removed mention of lists.

**Comment by ttimbers** [comment]
Some suggestions:

* I would add stressing the importance of run all, and running cells in order under the Running and Quitting Interactively section. I've observed many students who create disorganized code when they learn to code in the notebook (they somehow can remember in their heads which cells to run in which order, but another person would never be able to run their code).

* I am not sure about the value of showing how to create a data frame before importing csv as a data frame. I think most people will do the latter in their workflow and rarely create a data frame from scratch.

* Since it is relatively trivial to export a csv from excel, I think we could skip How tor read data from Excel spreadsheets directly (needs another library). Only showing how to import .csv will hopefully encourage folks to save their own data as a .csv as opposed to .xls.

**Comment by ttimbers** [comment]
Also, can we please do plotting via Pandas, it is much simpler for simple cases.

**Comment by gvwilson** [comment]
Addressed @ttimbers comments in 21acba6203.

**Comment by PBarmby** [comment]
This version looks pretty good; I don't have anything to add. I am really curious to know how this would go with real learners.

**Comment by gvwilson** [comment]
Me too :-)  Shall we try it out some time?

**Comment by tobyhodges** [comment]
I agree - the only way to know what else needs tweaking in the material and timings is by testing it on live subjects. I'm aiming to organise a workshop later this year and could use that as an opportunity to try the lesson. Of course, you'll probably want someone with more SWC experience to do this, and sooner too!

**Pull request merged**
