### PR TITLE
an illustration of indexing #168

### PR DESCRIPTION
**Pull request by echism**
svg created and added

### CODE REVIEW

**Comment by echism** [comment]
linking https://github.com/swcarpentry/python-novice-gapminder/issues/168

**Comment by alee** [comment]
thanks for the PR, the diagram looks great! LGTM, though if @maxim-belkin has time he may have some suggestions on tidying up the SVG for maintainability (see https://github.com/swcarpentry/python-novice-gapminder/pull/350 for an example)

**Comment by maxim-belkin** [comment]
The image is, in fact, very nice. In the current form, however, it can not be cleaned up as all text elements were converted to paths. I don't know which editor was used to create the file, but please try to find a checkbox or a setting that is responsible for that and uncheck it. Ideally, you would have `text` and `rect` elements only. Maybe `textspan`s.

To solve the issue that @alee mentions above, you can "increase" the size of the `viewBox` in horizontal dimension, that is, change `viewBox="0 0 533 191"` to something like `viewBox="0 0 633 191"`.

**Comment by echism** [comment]
Hey all, I have some amount of digital media training and it's generally considered best practice to do the text as paths/outlines because it renders differently on the user end as text depending on whether they have the fonts and other considerations; I'll show you a funky rendering I saw of the reference graphic you provided along these lines. If you want me to proceed with those changes anyway, it's super easily done. It may be in this particular use case that it's best to leave it as text, for the ease of maintenance. I just wanted to double check. 

viewing

**Comment by maxim-belkin** [comment]
This may be true for fancy fonts or for unusual operating systems and internet browsers but not for the ones that majority of browsers have -- Arial, Times, Times New Roman. That's why we don't specify fonts in SVG files -- the default one (Arial) is not fancy but gets the job done.

As you noted, we're trying to make SVG files easy to maintain. Imagine Python switches to 1-based indexing and we have to update the four indexes -- we'd have to start from scratch. In fact, any change would require someone to start from scratch. That's why "paths" are good but only as long as you have the original with text not converted to paths.

Could you please describe how we can reproduce that finicky rendering that you observed?

> If you want me to proceed with those changes anyway, it's super easily done. It may be in this particular use case that it's best to leave it as text, for the ease of maintenance. I just wanted to double check.

Yes, please proceed with these changes. Thank you

> Hey all, I have some amount of digital media training

Glad to have someone with this type on training on board! Please feel free to review/redo/convert to SVG figures in other lessons as well.

**Comment by echism** [comment]
Understood. I think it's the edge browser rendering the SVG that way, but it may additionally have some peculiarity from windows (10) or some fine point of my particular font set

**Comment by echism** [comment]
Changes are in! SVG is now smaller and not path-ized

**Comment by maxim-belkin** [comment]
Could you please unminimize it and remove unnecessaty classes/defs?

**Comment by maxim-belkin** [comment]
The spacing between characters is uneven.

**Comment by echism** [comment]
I've redone it using the program you all recommend in your docs. This is different from my typical workflow but I think it's about where you want it

**Comment by maxim-belkin** [comment]
Could you please post a screenshot of how it looks in your browser? It's a bit wrong in my Firefox.

**Comment by echism** [comment]
Untitled
In chrome and edge it looks like this.

**Comment by maxim-belkin** [comment]
Could you please post a screenshot of the following figure in your browser:

```svg
<svg height="400" width="900" xmlns="http://www.w3.org/2000/svg">
  <rect x="40" y="140" width="48" height="110" fill="#b3ef54" />
  <text font-size="80" x="40" y="80"><tspan fill="#800080">print</tspan>(atom_name[0])</text>
  <text font-size="80" x="40" y="200" font-family="monospace">helium</text>
  <text font-size="30" x="40" y="240" font-family="monospace">
    <tspan dx="14">0</tspan>
    <tspan dx="14">1</tspan>
    <tspan dx="14">2</tspan>
    <tspan dx="14">3</tspan>
    <tspan dx="14">4</tspan>
    <tspan dx="14">5</tspan>
  </text>
</svg>
```

**Comment by maxim-belkin** [comment]
for some reason letter-spacing does not work for me.

**Comment by maxim-belkin** [comment]
We might have to change those `dx`es from 14 to 12.5 and the starting position from 40 to 42:
```svg
<svg height="400" width="900" xmlns="http://www.w3.org/2000/svg">
  <rect x="40" y="140" width="48" height="110" fill="#b3ef54" stroke="#000"/>
  <rect x="88" y="140" width="48" height="110" fill="#93ef54" stroke="#000"/>
  <rect x="136" y="140" width="48" height="110" fill="#73ef54" stroke="#000"/>
  <rect x="184" y="140" width="48" height="110" fill="#53ef54" stroke="#000"/>
  <rect x="232" y="140" width="48" height="110" fill="#33ef54" stroke="#000"/>
  <rect x="280" y="140" width="48" height="110" fill="#13ef54" stroke="#000"/>
  <text font-size="80" x="40" y="80"><tspan fill="#800080">print</tspan>(atom_name[0])</text>
  <text font-size="80" x="40" y="200" font-family="monospace">helium</text>
  <text font-size="30" x="42" y="240" font-family="monospace" fill="#444">
    <tspan dx="12.5">0</tspan>
    <tspan dx="12.5">1</tspan>
    <tspan dx="12.5">2</tspan>
    <tspan dx="12.5">3</tspan>
    <tspan dx="12.5">4</tspan>
    <tspan dx="12.5">5</tspan>
  </text>
</svg>
```
image

**Comment by echism** [comment]
screenshot
the 14 works better in my browsers

**Comment by maxim-belkin** [comment]
interesting... This means that your "monospace" font is different from mine and (most likely) we have to express spacing in terms of `em`s... which is not cool as we can't express everything in terms of `em`s (`rect`'s dimensions)

**Comment by maxim-belkin** [comment]
If we use `text-anchor="middle"` on all `textspan` elements and split the word "helium" into `textspan`s, then we're guaranteed to have proper positioning of characters regardless of the font.

**Comment by echism** [comment]
This looks okay to me except that the zero in the large font is for some reason not the same design as the smaller zero

<svg height="400" width="900" xmlns="http://www.w3.org/2000/svg">
  <rect x="40" y="140" width="48" height="110" fill="#b3ef54"/>
  <rect x="616" y="20" width="44" height="80" fill="#b3ef54" />
  <text font-size="80" x="40" y="80"><tspan fill="#800080">print</tspan>(atom_name[0])</text>
  <text font-size="80" x="40" y="200" font-family="monospace">
	<tspan>h</tspan>
    <tspan>e</tspan>
    <tspan>l</tspan>
    <tspan>i</tspan>
    <tspan>u</tspan>
    <tspan>m</tspan></text>
  <text font-size="30" x="2" y="240" font-family="monospace">
    <tspan dx="55">0</tspan>
    <tspan dx="55">1</tspan>
    <tspan dx="55">2</tspan>
    <tspan dx="55">3</tspan>
    <tspan dx="55">4</tspan>
    <tspan dx="55">5</tspan>
  </text>
</svg>

**Comment by maxim-belkin** [comment]
I think this should be cross-platform and cross-browser  
```svg
<svg height="400" width="900" xmlns="http://www.w3.org/2000/svg">
  <rect x="40"  y="140" width="48" height="110" fill="#b3ef54" stroke="#000"/>
  <rect x="88"  y="140" width="48" height="110" fill="#a3df44" stroke="#000"/>
  <rect x="136" y="140" width="48" height="110" fill="#93cf34" stroke="#000"/>
  <rect x="184" y="140" width="48" height="110" fill="#83bf24" stroke="#000"/>
  <rect x="232" y="140" width="48" height="110" fill="#73af14" stroke="#000"/>
  <rect x="280" y="140" width="48" height="110" fill="#639f04" stroke="#000"/>

  <text font-size="80" x="40" y="80"><tspan fill="#800080">print</tspan>(atom_name[0])</text>

  <g font-family="monospace" fill="#000" font-size="60" text-anchor="middle">
    <text x="65"  y="200">h</text>
    <text x="113" y="200">e</text>
    <text x="161" y="200">l</text>
    <text x="209" y="200">i</text>
    <text x="257" y="200">u</text>
    <text x="305" y="200">m</text>
  </g>

  <g font-family="monospace" fill="#333" font-size="20" text-anchor="middle">
    <text x="65"  y="240">0</text>
    <text x="113" y="240">1</text>
    <text x="161" y="240">2</text>
    <text x="209" y="240">3</text>
    <text x="257" y="240">4</text>
    <text x="305" y="240">5</text>
  </g>
</svg>
```
🤞

**Comment by echism** [comment]
Yeah that looks okay on mine except I would specify that print statement as monospace so the zeroes both have strikethrus

**Comment by maxim-belkin** [comment]
oh, sure -- my "monospace" doesn't have strikethroughs in 0s -- feel free to do that. In that case you can actually move `font-family="monospace"` up to the `<svg>` definition (you'll have to increase the width of the figure too) and remove it from both groups (see below).

@alee, I'm handing it off back to you.

Things to consider:
1. Do you want to keep those colorful rectangles? (I used them to check that letters are indeed monospace)
2. Positions of indices: should they be below or above the letters?
...

Thanks, @echism! It was a blast! I actually learned something new about SVG files myself :)

```svg
<svg height="400" width="1000" xmlns="http://www.w3.org/2000/svg" font-family="monospace">
  <rect x="40"  y="140" width="48" height="110" fill="#b3ef54" stroke="#000"/>
  <rect x="88"  y="140" width="48" height="110" fill="#a3df44" stroke="#000"/>
  <rect x="136" y="140" width="48" height="110" fill="#93cf34" stroke="#000"/>
  <rect x="184" y="140" width="48" height="110" fill="#83bf24" stroke="#000"/>
  <rect x="232" y="140" width="48" height="110" fill="#73af14" stroke="#000"/>
  <rect x="280" y="140" width="48" height="110" fill="#639f04" stroke="#000"/>

  <text font-size="80" x="40" y="80"><tspan fill="#800080">print</tspan>(atom_name[0])</text>

  <g fill="#000" font-size="60" text-anchor="middle">
    <text x="65"  y="200">h</text>
    <text x="113" y="200">e</text>
    <text x="161" y="200">l</text>
    <text x="209" y="200">i</text>
    <text x="257" y="200">u</text>
    <text x="305" y="200">m</text>
  </g>

  <g fill="#333" font-size="20" text-anchor="middle">
    <text x="65"  y="240">0</text>
    <text x="113" y="240">1</text>
    <text x="161" y="240">2</text>
    <text x="209" y="240">3</text>
    <text x="257" y="240">4</text>
    <text x="305" y="240">5</text>
  </g>
</svg>
```

**Comment by echism** [comment]
Ok awesome! I moved the indices above and omitted the value blocks to make it closer to the reference materials, but I did like the stroke around the rect so I kept that and made it a little less large on the page. I think this should do it?

**Comment by alee** [comment]
Looks great, thanks for all your work @echism and @maxim-belkin ! 👏 

I'll rename indexing.svg and change the reference and then we should be good to merge. Much appreciated!

**Comment by maxim-belkin** [comment]
@alee, I think you have to add empty lines around the image.

**Comment by alee** [comment]
ah, thanks for the heads up, just noticed that the rendering is off. Fixed!

**Comment by maxim-belkin** [comment]
no problem!

**Pull request merged**
